# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

FROM node:carbon

WORKDIR /usr/src/app

ENV NODE_ENV=production \
    SERVER_PORT=8080 \
    LOG_LEVEL=info

RUN git clone https://github.com/microsoft/openpaimarketplace.git && \
    cd openpaimarketplace && \
    git checkout v1.0.0 && \
    cd webportal_plugin && \
    yarn install --production=false && \
    yarn build

EXPOSE ${SERVER_PORT}

WORKDIR /usr/src/app/openpaimarketplace/webportal_plugin

CMD ["yarn", "start"]
