# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

FROM node:carbon

WORKDIR /usr/src/app

ENV NODE_ENV=production \
    SERVER_PORT=8080

git clone https://github.com/microsoft/openpaimarketplace.git

# Install dev-dependencies when building image
RUN yarn install --production=false
RUN npm run build

EXPOSE ${SERVER_PORT}

CMD ["npm", "start"]
